name: expense_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 
  fl_chart: ^0.68.0 

  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.1.4
  gap: ^3.0.1
  flashy_tab_bar2: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
   - assets/png/
  
